### ISSUE TITLE
Differnce in time domain EIS and PybaMM EIS 

### ISSUE THREAD

**Issue by Akila1993** [rish31415/pybamm-eis#24]
I am writing to you regarding the discussion I have opened [here](https://github.com/pybamm-team/PyBaMM/discussions/2974#discussioncomment-7584156) regarding the difference between time domain and frequency domain EIS profiles. 

According to the suggestion by Dr. Ferran when we reduce the amplitude of input current the difference between two profiles is reducing. According to Ferran it is because pybamm-eis uses a linearised version of the model so it is only an approximation. 

Could you please elaborate this behaviour further like how (what equations) it is linearised or if we could use the nonlinear model / or linear model to match the Okane 2022 parameter set and the model. Or please provide any reference for pybamm-eis.

Thank you.

**Comment by rtimms** [comment]
Fixed by https://github.com/pybamm-team/PyBaMM/pull/4139
